-- =============================================================================
-- 0018 — Villes du Sénégal : 14 régions, 46 départements, 553 communes (source :
-- découpage administratif issu du décret n° 2014-829 (Acte III de la décentralisation), liste
-- consolidée depuis Wikipédia « Communes of Senegal » consultée le 27/09/2026). Table de référence
-- lisible par tout utilisateur connecté. Les stations sont reliées à une commune (« Autre » sinon).
-- =============================================================================
create extension if not exists unaccent with schema extensions;

create table public.sn_regions (
  code text primary key,
  name text not null unique
);
create table public.sn_departments (
  code text primary key,
  name text not null,
  region_code text not null references public.sn_regions (code),
  unique (region_code, name)
);
create table public.sn_communes (
  code text primary key,
  name text not null,
  department_code text not null references public.sn_departments (code),
  unique (department_code, name)
);
comment on table public.sn_communes is 'Communes du Sénégal (référence, lecture seule). Code = région/département/commune en minuscules sans accent.';

-- Normalisation pour la recherche et le rattachement : minuscules, sans accents ni ponctuation.
create or replace function public.normaliser_localite(p text)
returns text
language sql
immutable
set search_path = ''
as $$
  select trim(both '-' from regexp_replace(lower(extensions.unaccent(coalesce(p, ''))), '[^a-z0-9]+', '-', 'g'));
$$;
revoke all on function public.normaliser_localite(text) from public, anon;
grant execute on function public.normaliser_localite(text) to authenticated, service_role;

insert into public.sn_regions (code, name) values
  ('dakar', 'Dakar'),
  ('diourbel', 'Diourbel'),
  ('fatick', 'Fatick'),
  ('kaffrine', 'Kaffrine'),
  ('kaolack', 'Kaolack'),
  ('kedougou', 'Kédougou'),
  ('kolda', 'Kolda'),
  ('louga', 'Louga'),
  ('matam', 'Matam'),
  ('saint-louis', 'Saint-Louis'),
  ('sedhiou', 'Sédhiou'),
  ('tambacounda', 'Tambacounda'),
  ('thies', 'Thiès'),
  ('ziguinchor', 'Ziguinchor');
insert into public.sn_departments (code, name, region_code) values
  ('dakar/dakar', 'Dakar', 'dakar'),
  ('dakar/guediawaye', 'Guédiawaye', 'dakar'),
  ('dakar/pikine', 'Pikine', 'dakar'),
  ('dakar/rufisque', 'Rufisque', 'dakar'),
  ('dakar/keur-massar', 'Keur Massar', 'dakar'),
  ('diourbel/bambey', 'Bambey', 'diourbel'),
  ('diourbel/diourbel', 'Diourbel', 'diourbel'),
  ('diourbel/mbacke', 'Mbacké', 'diourbel'),
  ('fatick/fatick', 'Fatick', 'fatick'),
  ('fatick/foundiougne', 'Foundiougne', 'fatick'),
  ('fatick/gossas', 'Gossas', 'fatick'),
  ('kaffrine/birkelane', 'Birkelane', 'kaffrine'),
  ('kaffrine/kaffrine', 'Kaffrine', 'kaffrine'),
  ('kaffrine/koungheul', 'Koungheul', 'kaffrine'),
  ('kaffrine/malem-hodar', 'Malem-Hodar', 'kaffrine'),
  ('kaolack/guinguineo', 'Guinguinéo', 'kaolack'),
  ('kaolack/kaolack', 'Kaolack', 'kaolack'),
  ('kaolack/nioro-du-rip', 'Nioro du Rip', 'kaolack'),
  ('kedougou/kedougou', 'Kédougou', 'kedougou'),
  ('kedougou/salemata', 'Salémata', 'kedougou'),
  ('kedougou/saraya', 'Saraya', 'kedougou'),
  ('kolda/kolda', 'Kolda', 'kolda'),
  ('kolda/medina-yoro-foulah', 'Médina Yoro Foulah', 'kolda'),
  ('kolda/velingara', 'Vélingara', 'kolda'),
  ('louga/kebemer', 'Kébémer', 'louga'),
  ('louga/linguere', 'Linguère', 'louga'),
  ('louga/louga', 'Louga', 'louga'),
  ('matam/kanel', 'Kanel', 'matam'),
  ('matam/matam', 'Matam', 'matam'),
  ('matam/ranerou-ferlo', 'Ranérou Ferlo', 'matam'),
  ('saint-louis/dagana', 'Dagana', 'saint-louis'),
  ('saint-louis/podor', 'Podor', 'saint-louis'),
  ('saint-louis/saint-louis', 'Saint-Louis', 'saint-louis'),
  ('sedhiou/bounkiling', 'Bounkiling', 'sedhiou'),
  ('sedhiou/goudomp', 'Goudomp', 'sedhiou'),
  ('sedhiou/sedhiou', 'Sédhiou', 'sedhiou'),
  ('tambacounda/bakel', 'Bakel', 'tambacounda'),
  ('tambacounda/goudiry', 'Goudiry', 'tambacounda'),
  ('tambacounda/koumpentoum', 'Koumpentoum', 'tambacounda'),
  ('tambacounda/tambacounda', 'Tambacounda', 'tambacounda'),
  ('thies/mbour', 'Mbour', 'thies'),
  ('thies/thies', 'Thiès', 'thies'),
  ('thies/tivaouane', 'Tivaouane', 'thies'),
  ('ziguinchor/bignona', 'Bignona', 'ziguinchor'),
  ('ziguinchor/oussouye', 'Oussouye', 'ziguinchor'),
  ('ziguinchor/ziguinchor', 'Ziguinchor', 'ziguinchor');
insert into public.sn_communes (code, name, department_code) values
  ('dakar/dakar/biscuiterie', 'Biscuiterie', 'dakar/dakar'),
  ('dakar/dakar/camberene', 'Cambérène', 'dakar/dakar'),
  ('dakar/dakar/colobane-fass-gueule-tapee', 'Colobane / Fass / Gueule Tapée', 'dakar/dakar'),
  ('dakar/dakar/dakar-plateau', 'Dakar-Plateau', 'dakar/dakar'),
  ('dakar/dakar/dieuppeul-derkle', 'Dieuppeul-Derklé', 'dakar/dakar'),
  ('dakar/dakar/fann-point-e-amitie', 'Fann-Point E-Amitié', 'dakar/dakar'),
  ('dakar/dakar/goree', 'Gorée', 'dakar/dakar'),
  ('dakar/dakar/grand-dakar', 'Grand Dakar', 'dakar/dakar'),
  ('dakar/dakar/grand-yoff', 'Grand Yoff', 'dakar/dakar'),
  ('dakar/dakar/hann-bel-air', 'Hann Bel-Air', 'dakar/dakar'),
  ('dakar/dakar/hlm', 'HLM', 'dakar/dakar'),
  ('dakar/dakar/medina', 'Médina', 'dakar/dakar'),
  ('dakar/dakar/mermoz-sacre-c-ur', 'Mermoz-Sacré-Cœur', 'dakar/dakar'),
  ('dakar/dakar/ngor', 'Ngor', 'dakar/dakar'),
  ('dakar/dakar/ouakam', 'Ouakam', 'dakar/dakar'),
  ('dakar/dakar/parcelles-assainies', 'Parcelles Assainies', 'dakar/dakar'),
  ('dakar/dakar/patte-d-oie', 'Patte d''Oie', 'dakar/dakar'),
  ('dakar/dakar/sicap-liberte', 'Sicap-Liberté', 'dakar/dakar'),
  ('dakar/dakar/yoff', 'Yoff', 'dakar/dakar'),
  ('dakar/guediawaye/golf-sud', 'Golf Sud', 'dakar/guediawaye'),
  ('dakar/guediawaye/medina-gounass', 'Médina Gounass', 'dakar/guediawaye'),
  ('dakar/guediawaye/ndiareme-limamoulaye', 'Ndiarème Limamoulaye', 'dakar/guediawaye'),
  ('dakar/guediawaye/sam-notaire', 'Sam Notaire', 'dakar/guediawaye'),
  ('dakar/guediawaye/wakhinane-nimzatt', 'Wakhinane Nimzatt', 'dakar/guediawaye'),
  ('dakar/pikine/dalifort', 'Dalifort', 'dakar/pikine'),
  ('dakar/pikine/diacksao', 'Diacksao', 'dakar/pikine'),
  ('dakar/pikine/diamaguene-sicap-mbao', 'Diamaguène / Sicap Mbao', 'dakar/pikine'),
  ('dakar/pikine/djidah-thiaroye-kaw', 'Djidah Thiaroye Kaw', 'dakar/pikine'),
  ('dakar/pikine/guinaw-rail-nord', 'Guinaw Rail Nord', 'dakar/pikine'),
  ('dakar/pikine/guinaw-rail-sud', 'Guinaw Rail Sud', 'dakar/pikine'),
  ('dakar/pikine/mbao', 'Mbao', 'dakar/pikine'),
  ('dakar/pikine/pikine-est', 'Pikine Est', 'dakar/pikine'),
  ('dakar/pikine/pikine-ouest', 'Pikine Ouest', 'dakar/pikine'),
  ('dakar/pikine/pikine-sud', 'Pikine Sud', 'dakar/pikine'),
  ('dakar/pikine/thiaroye-gare', 'Thiaroye-Gare', 'dakar/pikine'),
  ('dakar/pikine/thiaroye-sur-mer', 'Thiaroye-sur-Mer', 'dakar/pikine'),
  ('dakar/rufisque/bambylor', 'Bambylor', 'dakar/rufisque'),
  ('dakar/rufisque/bargny', 'Bargny', 'dakar/rufisque'),
  ('dakar/rufisque/diamniadio', 'Diamniadio', 'dakar/rufisque'),
  ('dakar/rufisque/rufisque-est', 'Rufisque Est', 'dakar/rufisque'),
  ('dakar/rufisque/rufisque-nord', 'Rufisque Nord', 'dakar/rufisque'),
  ('dakar/rufisque/rufisque-ouest', 'Rufisque Ouest', 'dakar/rufisque'),
  ('dakar/rufisque/sangalkam', 'Sangalkam', 'dakar/rufisque'),
  ('dakar/rufisque/sebikhotane', 'Sébikhotane', 'dakar/rufisque'),
  ('dakar/rufisque/sendou', 'Sendou', 'dakar/rufisque'),
  ('dakar/rufisque/tivaouane-peulh-niaga', 'Tivaouane Peulh-Niaga', 'dakar/rufisque'),
  ('dakar/rufisque/yene', 'Yène', 'dakar/rufisque'),
  ('dakar/keur-massar/jaxaay-parcelles', 'Jaxaay-Parcelles', 'dakar/keur-massar'),
  ('dakar/keur-massar/keur-massar-nord', 'Keur Massar Nord', 'dakar/keur-massar'),
  ('dakar/keur-massar/keur-massar-sud', 'Keur Massar Sud', 'dakar/keur-massar'),
  ('dakar/keur-massar/malika', 'Malika', 'dakar/keur-massar'),
  ('dakar/keur-massar/yeumbeul-nord', 'Yeumbeul Nord', 'dakar/keur-massar'),
  ('dakar/keur-massar/yeumbeul-sud', 'Yeumbeul Sud', 'dakar/keur-massar'),
  ('diourbel/bambey/baba-garage', 'Baba Garage', 'diourbel/bambey'),
  ('diourbel/bambey/bambey', 'Bambey', 'diourbel/bambey'),
  ('diourbel/bambey/dinguiraye', 'Dinguiraye', 'diourbel/bambey'),
  ('diourbel/bambey/gawane', 'Gawane', 'diourbel/bambey'),
  ('diourbel/bambey/keur-samba-kane', 'Keur Samba Kane', 'diourbel/bambey'),
  ('diourbel/bambey/lambaye', 'Lambaye', 'diourbel/bambey'),
  ('diourbel/bambey/ndangalma', 'Ndangalma', 'diourbel/bambey'),
  ('diourbel/bambey/ndondol', 'Ndondol', 'diourbel/bambey'),
  ('diourbel/bambey/ngogom', 'Ngogom', 'diourbel/bambey'),
  ('diourbel/bambey/ngoye', 'Ngoye', 'diourbel/bambey'),
  ('diourbel/bambey/refane', 'Réfane', 'diourbel/bambey'),
  ('diourbel/bambey/thiakhar', 'Thiakhar', 'diourbel/bambey'),
  ('diourbel/diourbel/diourbel', 'Diourbel', 'diourbel/diourbel'),
  ('diourbel/diourbel/gade-escale', 'Gade Escale', 'diourbel/diourbel'),
  ('diourbel/diourbel/keur-ngalgou', 'Keur Ngalgou', 'diourbel/diourbel'),
  ('diourbel/diourbel/dankh-sene', 'Dankh Sène', 'diourbel/diourbel'),
  ('diourbel/diourbel/ndindy', 'Ndindy', 'diourbel/diourbel'),
  ('diourbel/diourbel/ndoulo', 'Ndoulo', 'diourbel/diourbel'),
  ('diourbel/diourbel/ngohe', 'Ngohé', 'diourbel/diourbel'),
  ('diourbel/diourbel/patar', 'Patar', 'diourbel/diourbel'),
  ('diourbel/diourbel/taiba-moutoupha', 'Taïba Moutoupha', 'diourbel/diourbel'),
  ('diourbel/diourbel/tocky-gare', 'Tocky-Gare', 'diourbel/diourbel'),
  ('diourbel/diourbel/touba-lappe', 'Touba Lappé', 'diourbel/diourbel'),
  ('diourbel/diourbel/toure-mbonde', 'Touré Mbonde', 'diourbel/diourbel'),
  ('diourbel/mbacke/dalla-ngabou', 'Dalla Ngabou', 'diourbel/mbacke'),
  ('diourbel/mbacke/darou-nahim', 'Darou Nahim', 'diourbel/mbacke'),
  ('diourbel/mbacke/darou-salam-typ', 'Darou Salam Typ', 'diourbel/mbacke'),
  ('diourbel/mbacke/dendey-gouyegui', 'Dendey Gouyegui', 'diourbel/mbacke'),
  ('diourbel/mbacke/kael', 'Kael', 'diourbel/mbacke'),
  ('diourbel/mbacke/madina', 'Madina', 'diourbel/mbacke'),
  ('diourbel/mbacke/mbacke', 'Mbacké', 'diourbel/mbacke'),
  ('diourbel/mbacke/missirah', 'Missirah', 'diourbel/mbacke'),
  ('diourbel/mbacke/ndioumane', 'Ndioumane', 'diourbel/mbacke'),
  ('diourbel/mbacke/nghaye', 'Nghaye', 'diourbel/mbacke'),
  ('diourbel/mbacke/sadio', 'Sadio', 'diourbel/mbacke'),
  ('diourbel/mbacke/taiba-thiekene', 'Taïba Thiékène', 'diourbel/mbacke'),
  ('diourbel/mbacke/taif', 'Taïf', 'diourbel/mbacke'),
  ('diourbel/mbacke/touba-fall', 'Touba Fall', 'diourbel/mbacke'),
  ('diourbel/mbacke/touba-mboul', 'Touba Mboul', 'diourbel/mbacke'),
  ('diourbel/mbacke/touba-mosquee', 'Touba Mosquée', 'diourbel/mbacke'),
  ('fatick/fatick/diakhao', 'Diakhao', 'fatick/fatick'),
  ('fatick/fatick/diaoule', 'Diaoulé', 'fatick/fatick'),
  ('fatick/fatick/diarrere', 'Diarrère', 'fatick/fatick'),
  ('fatick/fatick/diofior', 'Diofior', 'fatick/fatick'),
  ('fatick/fatick/diouroup', 'Diouroup', 'fatick/fatick'),
  ('fatick/fatick/djilasse', 'Djilasse', 'fatick/fatick'),
  ('fatick/fatick/fatick', 'Fatick', 'fatick/fatick'),
  ('fatick/fatick/fimela', 'Fimela', 'fatick/fatick'),
  ('fatick/fatick/loul-sessene', 'Loul Séssène', 'fatick/fatick'),
  ('fatick/fatick/mbellacadiao', 'Mbéllacadiao', 'fatick/fatick'),
  ('fatick/fatick/ndiob', 'Ndiob', 'fatick/fatick'),
  ('fatick/fatick/ngayokheme', 'Ngayokhème', 'fatick/fatick'),
  ('fatick/fatick/niakhar', 'Niakhar', 'fatick/fatick'),
  ('fatick/fatick/palmarin', 'Palmarin', 'fatick/fatick'),
  ('fatick/fatick/patar', 'Patar', 'fatick/fatick'),
  ('fatick/fatick/tattaguine', 'Tattaguine', 'fatick/fatick'),
  ('fatick/fatick/thiare-ndialgui', 'Thiaré Ndialgui', 'fatick/fatick'),
  ('fatick/foundiougne/bassoul', 'Bassoul', 'fatick/foundiougne'),
  ('fatick/foundiougne/diagane-barka', 'Diagane Barka', 'fatick/foundiougne'),
  ('fatick/foundiougne/dionewar', 'Dionewar', 'fatick/foundiougne'),
  ('fatick/foundiougne/diossong', 'Diossong', 'fatick/foundiougne'),
  ('fatick/foundiougne/djilor', 'Djilor', 'fatick/foundiougne'),
  ('fatick/foundiougne/djirnda', 'Djirnda', 'fatick/foundiougne'),
  ('fatick/foundiougne/foundiougne', 'Foundiougne', 'fatick/foundiougne'),
  ('fatick/foundiougne/karang-poste', 'Karang Poste', 'fatick/foundiougne'),
  ('fatick/foundiougne/keur-saloum-diane', 'Keur Saloum Diané', 'fatick/foundiougne'),
  ('fatick/foundiougne/keur-samba-gueye', 'Keur Samba Guèye', 'fatick/foundiougne'),
  ('fatick/foundiougne/mbam', 'Mbam', 'fatick/foundiougne'),
  ('fatick/foundiougne/niassene', 'Niassène', 'fatick/foundiougne'),
  ('fatick/foundiougne/nioro-alassane-tall', 'Nioro Alassane Tall', 'fatick/foundiougne'),
  ('fatick/foundiougne/passy', 'Passy', 'fatick/foundiougne'),
  ('fatick/foundiougne/sokone', 'Sokone', 'fatick/foundiougne'),
  ('fatick/foundiougne/soum', 'Soum', 'fatick/foundiougne'),
  ('fatick/foundiougne/toubacouta', 'Toubacouta', 'fatick/foundiougne'),
  ('fatick/gossas/colobane', 'Colobane', 'fatick/gossas'),
  ('fatick/gossas/gossas', 'Gossas', 'fatick/gossas'),
  ('fatick/gossas/mbar', 'Mbar', 'fatick/gossas'),
  ('fatick/gossas/ndiene-lagane', 'Ndiène Lagane', 'fatick/gossas'),
  ('fatick/gossas/ouadiour', 'Ouadiour', 'fatick/gossas'),
  ('fatick/gossas/patar-lia', 'Patar Lia', 'fatick/gossas'),
  ('kaffrine/birkelane/birkilane', 'Birkilane', 'kaffrine/birkelane'),
  ('kaffrine/birkelane/diamal', 'Diamal', 'kaffrine/birkelane'),
  ('kaffrine/birkelane/keur-mboucki', 'Keur Mboucki', 'kaffrine/birkelane'),
  ('kaffrine/birkelane/mabo', 'Mabo', 'kaffrine/birkelane'),
  ('kaffrine/birkelane/mbeuleup', 'Mbeuleup', 'kaffrine/birkelane'),
  ('kaffrine/birkelane/ndiognick', 'Ndiognick', 'kaffrine/birkelane'),
  ('kaffrine/birkelane/segre-gatta', 'Ségré Gatta', 'kaffrine/birkelane'),
  ('kaffrine/birkelane/touba-mbella', 'Touba Mbella', 'kaffrine/birkelane'),
  ('kaffrine/kaffrine/boulel', 'Boulel', 'kaffrine/kaffrine'),
  ('kaffrine/kaffrine/diamagadio', 'Diamagadio', 'kaffrine/kaffrine'),
  ('kaffrine/kaffrine/diokoul-mbelbouck', 'Diokoul Mbelbouck', 'kaffrine/kaffrine'),
  ('kaffrine/kaffrine/gniby', 'Gniby', 'kaffrine/kaffrine'),
  ('kaffrine/kaffrine/kaffrine', 'Kaffrine', 'kaffrine/kaffrine'),
  ('kaffrine/kaffrine/kahi', 'Kahi', 'kaffrine/kaffrine'),
  ('kaffrine/kaffrine/kathiotte', 'Kathiotte', 'kaffrine/kaffrine'),
  ('kaffrine/kaffrine/medinatoul-salam-ii', 'Médinatoul Salam II', 'kaffrine/kaffrine'),
  ('kaffrine/kaffrine/nganda', 'Nganda', 'kaffrine/kaffrine'),
  ('kaffrine/koungheul/fass-thiekene', 'Fass Thiékène', 'kaffrine/koungheul'),
  ('kaffrine/koungheul/ida-mouride', 'Ida Mouride', 'kaffrine/koungheul'),
  ('kaffrine/koungheul/koungheul', 'Koungheul', 'kaffrine/koungheul'),
  ('kaffrine/koungheul/lour-escale', 'Lour Escale', 'kaffrine/koungheul'),
  ('kaffrine/koungheul/maka-yop', 'Maka Yop', 'kaffrine/koungheul'),
  ('kaffrine/koungheul/missirah-wadene', 'Missirah Wadène', 'kaffrine/koungheul'),
  ('kaffrine/koungheul/gainte-pathe', 'Gainte Pathé', 'kaffrine/koungheul'),
  ('kaffrine/koungheul/ribot-escale', 'Ribot Escale', 'kaffrine/koungheul'),
  ('kaffrine/koungheul/saly-escale', 'Saly Escale', 'kaffrine/koungheul'),
  ('kaffrine/malem-hodar/darou-minam-2', 'Darou Minam 2', 'kaffrine/malem-hodar'),
  ('kaffrine/malem-hodar/dianke-souf', 'Dianké Souf', 'kaffrine/malem-hodar'),
  ('kaffrine/malem-hodar/khelcom', 'Khelcom', 'kaffrine/malem-hodar'),
  ('kaffrine/malem-hodar/malem-hodar', 'Malem-Hodar', 'kaffrine/malem-hodar'),
  ('kaffrine/malem-hodar/ndiobene-samba-lamo', 'Ndiobène Samba Lamo', 'kaffrine/malem-hodar'),
  ('kaffrine/malem-hodar/ndioum-ngainthe', 'Ndioum Ngainthe', 'kaffrine/malem-hodar'),
  ('kaffrine/malem-hodar/sagna', 'Sagna', 'kaffrine/malem-hodar'),
  ('kaolack/guinguineo/dara-mboss', 'Dara Mboss', 'kaolack/guinguineo'),
  ('kaolack/guinguineo/fass', 'Fass', 'kaolack/guinguineo'),
  ('kaolack/guinguineo/gagnick', 'Gagnick', 'kaolack/guinguineo'),
  ('kaolack/guinguineo/guinguineo', 'Guinguinéo', 'kaolack/guinguineo'),
  ('kaolack/guinguineo/khelcom-birane', 'Khelcom Birane', 'kaolack/guinguineo'),
  ('kaolack/guinguineo/mbadakhoune', 'Mbadakhoune', 'kaolack/guinguineo'),
  ('kaolack/guinguineo/mboss', 'Mboss', 'kaolack/guinguineo'),
  ('kaolack/guinguineo/ndiago', 'Ndiago', 'kaolack/guinguineo'),
  ('kaolack/guinguineo/ngathe-naoude', 'Ngathe Naoudé', 'kaolack/guinguineo'),
  ('kaolack/guinguineo/nguelou', 'Nguélou', 'kaolack/guinguineo'),
  ('kaolack/guinguineo/ourour', 'Ourour', 'kaolack/guinguineo'),
  ('kaolack/guinguineo/panal-wolof', 'Panal Wolof', 'kaolack/guinguineo'),
  ('kaolack/kaolack/dya', 'Dya', 'kaolack/kaolack'),
  ('kaolack/kaolack/gandiaye', 'Gandiaye', 'kaolack/kaolack'),
  ('kaolack/kaolack/kahone', 'Kahone', 'kaolack/kaolack'),
  ('kaolack/kaolack/kaolack', 'Kaolack', 'kaolack/kaolack'),
  ('kaolack/kaolack/keur-baka', 'Keur Baka', 'kaolack/kaolack'),
  ('kaolack/kaolack/latmingue', 'Latmingué', 'kaolack/kaolack'),
  ('kaolack/kaolack/ndiaffate', 'Ndiaffate', 'kaolack/kaolack'),
  ('kaolack/kaolack/ndiebel', 'Ndiébel', 'kaolack/kaolack'),
  ('kaolack/kaolack/ndiedieng', 'Ndiédieng', 'kaolack/kaolack'),
  ('kaolack/kaolack/ndofane', 'Ndofane', 'kaolack/kaolack'),
  ('kaolack/kaolack/sibassor', 'Sibassor', 'kaolack/kaolack'),
  ('kaolack/kaolack/thiare', 'Thiaré', 'kaolack/kaolack'),
  ('kaolack/kaolack/thiomby', 'Thiomby', 'kaolack/kaolack'),
  ('kaolack/nioro-du-rip/dabaly', 'Dabaly', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/darou-salam', 'Darou Salam', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/gainthe-kaye', 'Gainthe Kaye', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/kayemor', 'Kayemor', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/keur-maba-diakhou', 'Keur Maba Diakhou', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/keur-madiabel', 'Keur Madiabel', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/keur-madongo', 'Keur Madongo', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/keur-soce', 'Keur Socé', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/medina-sabakh', 'Médina Sabakh', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/ndrame-escale', 'Ndramé Escale', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/ngayene', 'Ngayène', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/nioro-du-rip', 'Nioro du Rip', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/paoskoto', 'Paoskoto', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/porokhane', 'Porokhane', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/taiba-niassene', 'Taïba Niassène', 'kaolack/nioro-du-rip'),
  ('kaolack/nioro-du-rip/wack-ngouna', 'Wack Ngouna', 'kaolack/nioro-du-rip'),
  ('kedougou/kedougou/bandafassi', 'Bandafassi', 'kedougou/kedougou'),
  ('kedougou/kedougou/dimboli', 'Dimboli', 'kedougou/kedougou'),
  ('kedougou/kedougou/dindefelo', 'Dindefelo', 'kedougou/kedougou'),
  ('kedougou/kedougou/fongolimbi', 'Fongolimbi', 'kedougou/kedougou'),
  ('kedougou/kedougou/kedougou', 'Kédougou', 'kedougou/kedougou'),
  ('kedougou/kedougou/ninefecha', 'Ninéfécha', 'kedougou/kedougou'),
  ('kedougou/kedougou/tomboroncoto', 'Tomboroncoto', 'kedougou/kedougou'),
  ('kedougou/salemata/dar-salam', 'Dar Salam', 'kedougou/salemata'),
  ('kedougou/salemata/ethiolo', 'Ethiolo', 'kedougou/salemata'),
  ('kedougou/salemata/oubadji', 'Oubadji', 'kedougou/salemata'),
  ('kedougou/salemata/salemata', 'Salémata', 'kedougou/salemata'),
  ('kedougou/saraya/bembou', 'Bembou', 'kedougou/saraya'),
  ('kedougou/saraya/dakateli', 'Dakateli', 'kedougou/saraya'),
  ('kedougou/saraya/kevoye', 'Kévoye', 'kedougou/saraya'),
  ('kedougou/saraya/khossanto', 'Khossanto', 'kedougou/saraya'),
  ('kedougou/saraya/medina-baffe', 'Médina Baffé', 'kedougou/saraya'),
  ('kedougou/saraya/missirah-sirimana', 'Missirah Sirimana', 'kedougou/saraya'),
  ('kedougou/saraya/sabodala', 'Sabodala', 'kedougou/saraya'),
  ('kedougou/saraya/saraya', 'Saraya', 'kedougou/saraya'),
  ('kolda/kolda/bagadadji', 'Bagadadji', 'kolda/kolda'),
  ('kolda/kolda/coumbacara', 'Coumbacara', 'kolda/kolda'),
  ('kolda/kolda/dabo', 'Dabo', 'kolda/kolda'),
  ('kolda/kolda/dialambere', 'Dialambéré', 'kolda/kolda'),
  ('kolda/kolda/dioulacolon', 'Dioulacolon', 'kolda/kolda'),
  ('kolda/kolda/guiro-yero-bocar', 'Guiro Yéro Bocar', 'kolda/kolda'),
  ('kolda/kolda/kolda', 'Kolda', 'kolda/kolda'),
  ('kolda/kolda/mampatim', 'Mampatim', 'kolda/kolda'),
  ('kolda/kolda/medina-cherif', 'Médina Chérif', 'kolda/kolda'),
  ('kolda/kolda/medina-el-hadj', 'Médina El Hadj', 'kolda/kolda'),
  ('kolda/kolda/salikegne', 'Salikégné', 'kolda/kolda'),
  ('kolda/kolda/sare-bidji', 'Saré Bidji', 'kolda/kolda'),
  ('kolda/kolda/sare-yoba-diega', 'Saré Yoba Diéga', 'kolda/kolda'),
  ('kolda/kolda/tankanto-escale', 'Tankanto Escale', 'kolda/kolda'),
  ('kolda/kolda/thietty', 'Thiétty', 'kolda/kolda'),
  ('kolda/medina-yoro-foulah/bignarabe', 'Bignarabé', 'kolda/medina-yoro-foulah'),
  ('kolda/medina-yoro-foulah/bourouco', 'Bourouco', 'kolda/medina-yoro-foulah'),
  ('kolda/medina-yoro-foulah/dinguiraye', 'Dinguiraye', 'kolda/medina-yoro-foulah'),
  ('kolda/medina-yoro-foulah/kerewane', 'Kéréwane', 'kolda/medina-yoro-foulah'),
  ('kolda/medina-yoro-foulah/koulinto', 'Koulinto', 'kolda/medina-yoro-foulah'),
  ('kolda/medina-yoro-foulah/medina-yoro-foulah', 'Médina Yoro Foulah', 'kolda/medina-yoro-foulah'),
  ('kolda/medina-yoro-foulah/ndorna', 'Ndorna', 'kolda/medina-yoro-foulah'),
  ('kolda/medina-yoro-foulah/niaming', 'Niaming', 'kolda/medina-yoro-foulah'),
  ('kolda/medina-yoro-foulah/pata', 'Pata', 'kolda/medina-yoro-foulah'),
  ('kolda/velingara/badion', 'Badion', 'kolda/velingara'),
  ('kolda/velingara/bonconto', 'Bonconto', 'kolda/velingara'),
  ('kolda/velingara/diaobe-kabendou', 'Diaobé-Kabendou', 'kolda/velingara'),
  ('kolda/velingara/fafacourou', 'Fafacourou', 'kolda/velingara'),
  ('kolda/velingara/kandia', 'Kandia', 'kolda/velingara'),
  ('kolda/velingara/kandiaye', 'Kandiaye', 'kolda/velingara'),
  ('kolda/velingara/kounkane', 'Kounkané', 'kolda/velingara'),
  ('kolda/velingara/linkering', 'Linkéring', 'kolda/velingara'),
  ('kolda/velingara/medina-gounass', 'Médina Gounass', 'kolda/velingara'),
  ('kolda/velingara/nemataba', 'Némataba', 'kolda/velingara'),
  ('kolda/velingara/ouassadou', 'Ouassadou', 'kolda/velingara'),
  ('kolda/velingara/pakour', 'Pakour', 'kolda/velingara'),
  ('kolda/velingara/paroumba', 'Paroumba', 'kolda/velingara'),
  ('kolda/velingara/sare-coly-salle', 'Saré Coly Sallé', 'kolda/velingara'),
  ('kolda/velingara/sinthiang-koundara', 'Sinthiang Koundara', 'kolda/velingara'),
  ('kolda/velingara/velingara', 'Vélingara', 'kolda/velingara'),
  ('louga/kebemer/bandegne-ouolof', 'Bandegne Ouolof', 'louga/kebemer'),
  ('louga/kebemer/darou-marnane', 'Darou Marnane', 'louga/kebemer'),
  ('louga/kebemer/darou-mousty', 'Darou Mousty', 'louga/kebemer'),
  ('louga/kebemer/diokoul-diawrigne', 'Diokoul Diawrigne', 'louga/kebemer'),
  ('louga/kebemer/gueoul', 'Guéoul', 'louga/kebemer'),
  ('louga/kebemer/kab-gaye', 'Kab Gaye', 'louga/kebemer'),
  ('louga/kebemer/kanene-ndiob', 'Kanène Ndiob', 'louga/kebemer'),
  ('louga/kebemer/kebemer', 'Kébémer', 'louga/kebemer'),
  ('louga/kebemer/loro', 'Loro', 'louga/kebemer'),
  ('louga/kebemer/mbacke-cajor', 'Mbacké Cajor', 'louga/kebemer'),
  ('louga/kebemer/mbadiane', 'Mbadiane', 'louga/kebemer'),
  ('louga/kebemer/ndande', 'Ndande', 'louga/kebemer'),
  ('louga/kebemer/ndoyene', 'Ndoyene', 'louga/kebemer'),
  ('louga/kebemer/ngourane-ouolof', 'Ngourane Ouolof', 'louga/kebemer'),
  ('louga/kebemer/sagatta-gueth', 'Sagatta Gueth', 'louga/kebemer'),
  ('louga/kebemer/sam-yabal', 'Sam Yabal', 'louga/kebemer'),
  ('louga/kebemer/thieppe', 'Thieppe', 'louga/kebemer'),
  ('louga/kebemer/thiolom-fall', 'Thiolom Fall', 'louga/kebemer'),
  ('louga/kebemer/touba-merina', 'Touba Mérina', 'louga/kebemer'),
  ('louga/linguere/affe-djoloff', 'Affé Djoloff', 'louga/linguere'),
  ('louga/linguere/barkedji', 'Barkédji', 'louga/linguere'),
  ('louga/linguere/boulal', 'Boulal', 'louga/linguere'),
  ('louga/linguere/dahra', 'Dahra', 'louga/linguere'),
  ('louga/linguere/dealy', 'Dealy', 'louga/linguere'),
  ('louga/linguere/dodji', 'Dodji', 'louga/linguere'),
  ('louga/linguere/gassane', 'Gassane', 'louga/linguere'),
  ('louga/linguere/kamb', 'Kamb', 'louga/linguere'),
  ('louga/linguere/labgar', 'Labgar', 'louga/linguere'),
  ('louga/linguere/linguere', 'Linguère', 'louga/linguere'),
  ('louga/linguere/mbeuleukhe', 'Mbeuleukhé', 'louga/linguere'),
  ('louga/linguere/mboula', 'Mboula', 'louga/linguere'),
  ('louga/linguere/ouarkhokh', 'Ouarkhokh', 'louga/linguere'),
  ('louga/linguere/sagatta-djolof', 'Sagatta Djolof', 'louga/linguere'),
  ('louga/linguere/tessekere-forage', 'Téssékéré Forage', 'louga/linguere'),
  ('louga/linguere/thiamene-djolof', 'Thiamène Djolof', 'louga/linguere'),
  ('louga/linguere/thiarny', 'Thiarny', 'louga/linguere'),
  ('louga/linguere/thiel', 'Thiel', 'louga/linguere'),
  ('louga/linguere/yang-yang', 'Yang-Yang', 'louga/linguere'),
  ('louga/louga/coki', 'Coki', 'louga/louga'),
  ('louga/louga/gande', 'Gande', 'louga/louga'),
  ('louga/louga/guet-ardo', 'Guet Ardo', 'louga/louga'),
  ('louga/louga/kele-gueye', 'Kéle Gueye', 'louga/louga'),
  ('louga/louga/keur-momar-sarr', 'Keur Momar Sarr', 'louga/louga'),
  ('louga/louga/leona', 'Léona', 'louga/louga'),
  ('louga/louga/louga', 'Louga', 'louga/louga'),
  ('louga/louga/mbediene', 'Mbédiène', 'louga/louga'),
  ('louga/louga/ndiagne', 'Ndiagne', 'louga/louga'),
  ('louga/louga/nguer-malal', 'Nguer Malal', 'louga/louga'),
  ('louga/louga/ngueune-sarr', 'Ngueune Sarr', 'louga/louga'),
  ('louga/louga/nguidile', 'Nguidilé', 'louga/louga'),
  ('louga/louga/niomre', 'Niomré', 'louga/louga'),
  ('louga/louga/pete-ouarack', 'Pété Ouarack', 'louga/louga'),
  ('louga/louga/sakal', 'Sakal', 'louga/louga'),
  ('louga/louga/syer', 'Syer', 'louga/louga'),
  ('louga/louga/thiamene-cayor', 'Thiamène Cayor', 'louga/louga'),
  ('matam/kanel/aoure', 'Aouré', 'matam/kanel'),
  ('matam/kanel/bokiladji', 'Bokiladji', 'matam/kanel'),
  ('matam/kanel/dembancane', 'Dembancané', 'matam/kanel'),
  ('matam/kanel/hamady-ounare', 'Hamady Ounaré', 'matam/kanel'),
  ('matam/kanel/kanel', 'Kanel', 'matam/kanel'),
  ('matam/kanel/ndendory', 'Ndendory', 'matam/kanel'),
  ('matam/kanel/odobere', 'Odobéré', 'matam/kanel'),
  ('matam/kanel/orkadiere', 'Orkadiere', 'matam/kanel'),
  ('matam/kanel/semme', 'Semmé', 'matam/kanel'),
  ('matam/kanel/sinthiou-bamambe-banadji', 'Sinthiou Bamambé-Banadji', 'matam/kanel'),
  ('matam/kanel/waounde', 'Waoundé', 'matam/kanel'),
  ('matam/kanel/wouro-sidy', 'Wouro Sidy', 'matam/kanel'),
  ('matam/matam/agnams', 'Agnams', 'matam/matam'),
  ('matam/matam/bokidiawe', 'Bokidiawé', 'matam/matam'),
  ('matam/matam/dabia', 'Dabia', 'matam/matam'),
  ('matam/matam/matam', 'Matam', 'matam/matam'),
  ('matam/matam/nabadji-civol', 'Nabadji Civol', 'matam/matam'),
  ('matam/matam/nguidjilone', 'Nguidjilone', 'matam/matam'),
  ('matam/matam/ogo', 'Ogo', 'matam/matam'),
  ('matam/matam/orefonde', 'Oréfondé', 'matam/matam'),
  ('matam/matam/ourossogui', 'Ourossogui', 'matam/matam'),
  ('matam/matam/thilogne', 'Thilogne', 'matam/matam'),
  ('matam/ranerou-ferlo/lougre-thioly', 'Lougré Thioly', 'matam/ranerou-ferlo'),
  ('matam/ranerou-ferlo/oudalaye', 'Oudalaye', 'matam/ranerou-ferlo'),
  ('matam/ranerou-ferlo/ranerou', 'Ranérou', 'matam/ranerou-ferlo'),
  ('matam/ranerou-ferlo/velingara', 'Vélingara', 'matam/ranerou-ferlo'),
  ('saint-louis/dagana/bokhol', 'Bokhol', 'saint-louis/dagana'),
  ('saint-louis/dagana/dagana', 'Dagana', 'saint-louis/dagana'),
  ('saint-louis/dagana/diama', 'Diama', 'saint-louis/dagana'),
  ('saint-louis/dagana/gae', 'Gaé', 'saint-louis/dagana'),
  ('saint-louis/dagana/mbane', 'Mbane', 'saint-louis/dagana'),
  ('saint-louis/dagana/ndombo-sandjiry', 'Ndombo Sandjiry', 'saint-louis/dagana'),
  ('saint-louis/dagana/ngnith', 'Ngnith', 'saint-louis/dagana'),
  ('saint-louis/dagana/richard-toll', 'Richard-Toll', 'saint-louis/dagana'),
  ('saint-louis/dagana/ronkh', 'Ronkh', 'saint-louis/dagana'),
  ('saint-louis/dagana/ross-bethio', 'Ross Béthio', 'saint-louis/dagana'),
  ('saint-louis/dagana/rosso', 'Rosso', 'saint-louis/dagana'),
  ('saint-louis/podor/aere-lao', 'Aéré Lao', 'saint-louis/podor'),
  ('saint-louis/podor/bode-lao', 'Bodé Lao', 'saint-louis/podor'),
  ('saint-louis/podor/boke-dialloube', 'Boké Dialloubé', 'saint-louis/podor'),
  ('saint-louis/podor/demette', 'Démette', 'saint-louis/podor'),
  ('saint-louis/podor/dodel', 'Dodel', 'saint-louis/podor'),
  ('saint-louis/podor/doumga-lao', 'Doumga Lao', 'saint-louis/podor'),
  ('saint-louis/podor/fanaye', 'Fanaye', 'saint-louis/podor'),
  ('saint-louis/podor/galoya-toucouleur', 'Galoya Toucouleur', 'saint-louis/podor'),
  ('saint-louis/podor/gamadji-sare', 'Gamadji Saré', 'saint-louis/podor'),
  ('saint-louis/podor/gollere', 'Golléré', 'saint-louis/podor'),
  ('saint-louis/podor/guede-chantier', 'Guédé Chantier', 'saint-louis/podor'),
  ('saint-louis/podor/guede-village', 'Guédé Village', 'saint-louis/podor'),
  ('saint-louis/podor/madina-diathbe', 'Madina Diathbé', 'saint-louis/podor'),
  ('saint-louis/podor/mbolo-birane', 'Mbolo Birane', 'saint-louis/podor'),
  ('saint-louis/podor/mboumba', 'Mboumba', 'saint-louis/podor'),
  ('saint-louis/podor/mery', 'Méry', 'saint-louis/podor'),
  ('saint-louis/podor/ndiandane', 'Ndiandane', 'saint-louis/podor'),
  ('saint-louis/podor/ndiayene-peindao', 'Ndiayène Peindao', 'saint-louis/podor'),
  ('saint-louis/podor/ndioum', 'Ndioum', 'saint-louis/podor'),
  ('saint-louis/podor/pete', 'Pété', 'saint-louis/podor'),
  ('saint-louis/podor/podor', 'Podor', 'saint-louis/podor'),
  ('saint-louis/podor/walalde', 'Walaldé', 'saint-louis/podor'),
  ('saint-louis/saint-louis/fass-ngom', 'Fass Ngom', 'saint-louis/saint-louis'),
  ('saint-louis/saint-louis/gandon', 'Gandon', 'saint-louis/saint-louis'),
  ('saint-louis/saint-louis/mpal', 'Mpal', 'saint-louis/saint-louis'),
  ('saint-louis/saint-louis/ndiebene-gandiole', 'Ndiébène Gandiole', 'saint-louis/saint-louis'),
  ('saint-louis/saint-louis/saint-louis', 'Saint-Louis', 'saint-louis/saint-louis'),
  ('sedhiou/bounkiling/bona', 'Bona', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/bounkiling', 'Bounkiling', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/diacounda', 'Diacounda', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/diambati', 'Diambati', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/diaroume', 'Diaroumé', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/djinany', 'Djinany', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/faoune', 'Faoune', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/inor', 'Inor', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/kandion-mangana', 'Kandion Mangana', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/madina-wandifa', 'Madina Wandifa', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/ndiamacouta', 'Ndiamacouta', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/ndiamalathiel', 'Ndiamalathiel', 'sedhiou/bounkiling'),
  ('sedhiou/bounkiling/tankon', 'Tankon', 'sedhiou/bounkiling'),
  ('sedhiou/goudomp/baghere', 'Baghère', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/diattacounda', 'Diattacounda', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/diouboudou', 'Diouboudou', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/djibanar', 'Djibanar', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/goudomp', 'Goudomp', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/kaour', 'Kaour', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/karantaba', 'Karantaba', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/kolibantang', 'Kolibantang', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/mangaroungou-santo', 'Mangaroungou Santo', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/niagha', 'Niagha', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/samine', 'Samine', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/simbandi-balante', 'Simbandi Balante', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/simbandi-brassou', 'Simbandi Brassou', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/tanaff', 'Tanaff', 'sedhiou/goudomp'),
  ('sedhiou/goudomp/yarang-balante', 'Yarang Balante', 'sedhiou/goudomp'),
  ('sedhiou/sedhiou/bambaly', 'Bambaly', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/bemet-bidjini', 'Bémet Bidjini', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/boghall', 'Boghall', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/diannah-ba', 'Diannah Ba', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/diannah-malary', 'Diannah Malary', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/diende', 'Diendé', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/djibabouya', 'Djibabouya', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/djiredji', 'Djiredji', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/koussy', 'Koussy', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/marsassoum', 'Marsassoum', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/oudoucar', 'Oudoucar', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/sakar', 'Sakar', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/sama-kanta-peulh', 'Sama Kanta Peulh', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/sansamba', 'Sansamba', 'sedhiou/sedhiou'),
  ('sedhiou/sedhiou/sedhiou', 'Sédhiou', 'sedhiou/sedhiou'),
  ('tambacounda/bakel/bakel', 'Bakel', 'tambacounda/bakel'),
  ('tambacounda/bakel/ballou', 'Ballou', 'tambacounda/bakel'),
  ('tambacounda/bakel/bele', 'Bélé', 'tambacounda/bakel'),
  ('tambacounda/bakel/diawara', 'Diawara', 'tambacounda/bakel'),
  ('tambacounda/bakel/gabou', 'Gabou', 'tambacounda/bakel'),
  ('tambacounda/bakel/gathiary', 'Gathiary', 'tambacounda/bakel'),
  ('tambacounda/bakel/kidira', 'Kidira', 'tambacounda/bakel'),
  ('tambacounda/bakel/madina-foulbe', 'Madina Foulbé', 'tambacounda/bakel'),
  ('tambacounda/bakel/moudery', 'Moudéry', 'tambacounda/bakel'),
  ('tambacounda/bakel/sadatou', 'Sadatou', 'tambacounda/bakel'),
  ('tambacounda/bakel/sinthiou-fissa', 'Sinthiou Fissa', 'tambacounda/bakel'),
  ('tambacounda/bakel/toumboura', 'Toumboura', 'tambacounda/bakel'),
  ('tambacounda/goudiry/bala', 'Bala', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/bani-israel', 'Bani Israël', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/boutoucoufara', 'Boutoucoufara', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/boynguel-bamba', 'Boynguel Bamba', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/dianke-makha', 'Dianké Makha', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/dougue', 'Dougué', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/goumbayel', 'Goumbayél', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/goudiry', 'Goudiry', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/koar', 'Koar', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/komoti', 'Komoti', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/kothiary', 'Kothiary', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/koulor', 'Koulor', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/koussan', 'Koussan', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/sinthiou-bocar-ali', 'Sinthiou Bocar Ali', 'tambacounda/goudiry'),
  ('tambacounda/goudiry/sinthiou-mamadou-boubou', 'Sinthiou Mamadou Boubou', 'tambacounda/goudiry'),
  ('tambacounda/koumpentoum/bamba-thialene', 'Bamba Thialène', 'tambacounda/koumpentoum'),
  ('tambacounda/koumpentoum/kahene', 'Kahène', 'tambacounda/koumpentoum'),
  ('tambacounda/koumpentoum/koumpentoum', 'Koumpentoum', 'tambacounda/koumpentoum'),
  ('tambacounda/koumpentoum/kouthia-gaydi', 'Kouthia Gaydi', 'tambacounda/koumpentoum'),
  ('tambacounda/koumpentoum/kouthiaba-wolof', 'Kouthiaba Wolof', 'tambacounda/koumpentoum'),
  ('tambacounda/koumpentoum/malem-niani', 'Malem Niani', 'tambacounda/koumpentoum'),
  ('tambacounda/koumpentoum/mereto', 'Méréto', 'tambacounda/koumpentoum'),
  ('tambacounda/koumpentoum/ndame', 'Ndame', 'tambacounda/koumpentoum'),
  ('tambacounda/koumpentoum/niani-toucouleur', 'Niani Toucouleur', 'tambacounda/koumpentoum'),
  ('tambacounda/koumpentoum/pass-koto', 'Pass Koto', 'tambacounda/koumpentoum'),
  ('tambacounda/koumpentoum/payar', 'Payar', 'tambacounda/koumpentoum'),
  ('tambacounda/koumpentoum/sinthiou-maleme', 'Sinthiou Malème', 'tambacounda/koumpentoum'),
  ('tambacounda/tambacounda/dialacoto', 'Dialacoto', 'tambacounda/tambacounda'),
  ('tambacounda/tambacounda/koussanar', 'Koussanar', 'tambacounda/tambacounda'),
  ('tambacounda/tambacounda/makacolibantang', 'Makacolibantang', 'tambacounda/tambacounda'),
  ('tambacounda/tambacounda/missirah', 'Missirah', 'tambacounda/tambacounda'),
  ('tambacounda/tambacounda/ndoga-babacar', 'Ndoga Babacar', 'tambacounda/tambacounda'),
  ('tambacounda/tambacounda/netteboulou', 'Néttéboulou', 'tambacounda/tambacounda'),
  ('tambacounda/tambacounda/tambacounda', 'Tambacounda', 'tambacounda/tambacounda'),
  ('thies/mbour/diass', 'Diass', 'thies/mbour'),
  ('thies/mbour/fissel', 'Fissel', 'thies/mbour'),
  ('thies/mbour/joal-fadiouth', 'Joal-Fadiouth', 'thies/mbour'),
  ('thies/mbour/mbour', 'Mbour', 'thies/mbour'),
  ('thies/mbour/malicounda', 'Malicounda', 'thies/mbour'),
  ('thies/mbour/ndiaganiao', 'Ndiaganiao', 'thies/mbour'),
  ('thies/mbour/ngaparou', 'Ngaparou', 'thies/mbour'),
  ('thies/mbour/nguekhokh', 'Nguékhokh', 'thies/mbour'),
  ('thies/mbour/ngueniene', 'Nguéniène', 'thies/mbour'),
  ('thies/mbour/popenguine-ndayane', 'Popenguine-Ndayane', 'thies/mbour'),
  ('thies/mbour/saly', 'Saly', 'thies/mbour'),
  ('thies/mbour/sandiara', 'Sandiara', 'thies/mbour'),
  ('thies/mbour/sessene', 'Séssène', 'thies/mbour'),
  ('thies/mbour/sindia', 'Sindia', 'thies/mbour'),
  ('thies/mbour/somone', 'Somone', 'thies/mbour'),
  ('thies/mbour/thiadiaye', 'Thiadiaye', 'thies/mbour'),
  ('thies/thies/diender', 'Diender', 'thies/thies'),
  ('thies/thies/fandene', 'Fandène', 'thies/thies'),
  ('thies/thies/kayar', 'Kayar', 'thies/thies'),
  ('thies/thies/keur-moussa', 'Keur Moussa', 'thies/thies'),
  ('thies/thies/khombole', 'Khombole', 'thies/thies'),
  ('thies/thies/ndieyene-sirah', 'Ndiéyène Sirah', 'thies/thies'),
  ('thies/thies/ngoudiane', 'Ngoudiane', 'thies/thies'),
  ('thies/thies/notto', 'Notto', 'thies/thies'),
  ('thies/thies/pout', 'Pout', 'thies/thies'),
  ('thies/thies/tassette', 'Tassette', 'thies/thies'),
  ('thies/thies/thienaba', 'Thiénaba', 'thies/thies'),
  ('thies/thies/thies-est', 'Thiès Est', 'thies/thies'),
  ('thies/thies/thies-nord', 'Thiès Nord', 'thies/thies'),
  ('thies/thies/thies-ouest', 'Thiès Ouest', 'thies/thies'),
  ('thies/thies/touba-toul', 'Touba Toul', 'thies/thies'),
  ('thies/thies/yaboyabo', 'Yaboyabo', 'thies/thies'),
  ('thies/tivaouane/cherif-lo', 'Chérif Lo', 'thies/tivaouane'),
  ('thies/tivaouane/darou-khoudoss', 'Darou Khoudoss', 'thies/tivaouane'),
  ('thies/tivaouane/koul', 'Koul', 'thies/tivaouane'),
  ('thies/tivaouane/mbayene', 'Mbayène', 'thies/tivaouane'),
  ('thies/tivaouane/mboro', 'Mboro', 'thies/tivaouane'),
  ('thies/tivaouane/meckhe', 'Meckhe', 'thies/tivaouane'),
  ('thies/tivaouane/meouane', 'Méouane', 'thies/tivaouane'),
  ('thies/tivaouane/merina-dakhar', 'Mérina Dakhar', 'thies/tivaouane'),
  ('thies/tivaouane/mont-rolland', 'Mont Rolland', 'thies/tivaouane'),
  ('thies/tivaouane/ngandiouf', 'Ngandiouf', 'thies/tivaouane'),
  ('thies/tivaouane/niakhene', 'Niakhene', 'thies/tivaouane'),
  ('thies/tivaouane/notto-gouye-diama', 'Notto Gouye Diama', 'thies/tivaouane'),
  ('thies/tivaouane/pambal', 'Pambal', 'thies/tivaouane'),
  ('thies/tivaouane/pekesse', 'Pékèsse', 'thies/tivaouane'),
  ('thies/tivaouane/pire-goureye', 'Pire Goureye', 'thies/tivaouane'),
  ('thies/tivaouane/taiba-ndiaye', 'Taïba Ndiaye', 'thies/tivaouane'),
  ('thies/tivaouane/thilmakha', 'Thilmakha', 'thies/tivaouane'),
  ('thies/tivaouane/tivaouane', 'Tivaouane', 'thies/tivaouane'),
  ('ziguinchor/bignona/balinghore', 'Balinghore', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/bignona', 'Bignona', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/boutoupa-camaracounda', 'Boutoupa-Camaracounda', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/diegoune', 'Diégoune', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/diouloulou', 'Diouloulou', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/djibidione', 'Djibidione', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/djinaky', 'Djinaky', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/kafountine', 'Kafountine', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/kartiack', 'Kartiack', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/kataba-1', 'Kataba 1', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/mangagoulack', 'Mangagoulack', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/niamone', 'Niamone', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/oulampane', 'Oulampane', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/ouonck', 'Ouonck', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/sindian', 'Sindian', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/suelle', 'Suelle', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/tenghory', 'Tenghory', 'ziguinchor/bignona'),
  ('ziguinchor/bignona/thionck-essyl', 'Thionck Essyl', 'ziguinchor/bignona'),
  ('ziguinchor/oussouye/diembering', 'Diembéring', 'ziguinchor/oussouye'),
  ('ziguinchor/oussouye/enampore', 'Enampore', 'ziguinchor/oussouye'),
  ('ziguinchor/oussouye/mlomp', 'Mlomp', 'ziguinchor/oussouye'),
  ('ziguinchor/oussouye/oukout', 'Oukout', 'ziguinchor/oussouye'),
  ('ziguinchor/oussouye/oussouye', 'Oussouye', 'ziguinchor/oussouye'),
  ('ziguinchor/oussouye/santhiaba-manjacque', 'Santhiaba Manjacque', 'ziguinchor/oussouye'),
  ('ziguinchor/ziguinchor/adeane', 'Adéane', 'ziguinchor/ziguinchor'),
  ('ziguinchor/ziguinchor/coubalan', 'Coubalan', 'ziguinchor/ziguinchor'),
  ('ziguinchor/ziguinchor/niaguis', 'Niaguis', 'ziguinchor/ziguinchor'),
  ('ziguinchor/ziguinchor/nyassia', 'Nyassia', 'ziguinchor/ziguinchor'),
  ('ziguinchor/ziguinchor/ziguinchor', 'Ziguinchor', 'ziguinchor/ziguinchor');

create index sn_communes_search_idx on public.sn_communes (public.normaliser_localite(name));

alter table public.sn_regions enable row level security;
alter table public.sn_departments enable row level security;
alter table public.sn_communes enable row level security;
create policy sn_regions_select_authenticated on public.sn_regions for select to authenticated using (auth.uid() is not null);
create policy sn_departments_select_authenticated on public.sn_departments for select to authenticated using (auth.uid() is not null);
create policy sn_communes_select_authenticated on public.sn_communes for select to authenticated using (auth.uid() is not null);
revoke all on public.sn_regions, public.sn_departments, public.sn_communes from anon;
revoke insert, update, delete on public.sn_regions, public.sn_departments, public.sn_communes from authenticated;

-- Stations : commune de référence (null = « Autre », la ville libre reste dans city).
alter table public.stations add column commune_code text references public.sn_communes (code) on delete set null;
comment on column public.stations.commune_code is 'Commune de référence (sn_communes). Null = localité « Autre » saisie librement dans city.';
update public.stations s
set commune_code = c.code, city = c.name
from public.sn_communes c
where s.commune_code is null
  and public.normaliser_localite(s.city) = public.normaliser_localite(c.name)
  and (select count(*) from public.sn_communes c2 where public.normaliser_localite(c2.name) = public.normaliser_localite(s.city)) = 1;

-- Localisation complète d'une station (commune, département, région).
create or replace function public.station_localite(p_station_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'city', s.city,
    'commune', c.name,
    'commune_code', c.code,
    'department', d.name,
    'department_code', d.code,
    'region', r.name,
    'region_code', r.code
  )
  from public.stations s
  left join public.sn_communes c on c.code = s.commune_code
  left join public.sn_departments d on d.code = c.department_code
  left join public.sn_regions r on r.code = d.region_code
  where s.id = p_station_id and s.organization_id in (select public.current_org_ids());
$$;
revoke all on function public.station_localite(uuid) from public, anon;
grant execute on function public.station_localite(uuid) to authenticated;

